### ISSUE TITLE
CTV Bug

### ISSUE THREAD

**Issue by ghost** [stabbedbybrick/freevine#35] opened 2023-12-11 21:25 UTC

**Comment by stabbedbybrick** [comment] 2023-12-12 08:59
Hi,

You can get 1080p for Punk'd as well. The problem is that the video id format is different so the init fails. 

This seems to happen more often now, so I'll add proper id lookups in next update. You should never hardcode stuff like this anyway, and I'm kind of surprised it's worked as well as it did for such a long time. 

Thanks for letting me know!

**Comment by stabbedbybrick** [comment] 2023-12-23 16:39
This should now be fixed in the latest update.

**Comment by stabbedbybrick** [comment] 2023-12-28 13:42
Great! Glad to hear it

**Closed as completed by stabbedbybrick** 2023-12-28 13:42 UTC
Labels: bug
