### ISSUE TITLE
Download complete season doesn't seem to work?

### ISSUE THREAD

**Issue by OevreFlataeker** [stabbedbybrick/freevine#43] opened 2023-12-28 10:25 UTC
With UKTV Play the "Download Complete Season" doesn't properly work:

There are 3 seasons linked at https://uktvplay.co.uk/shows/secrets-of-the-london-underground/watch-online - Entering this URL and selecting "Download Complete season" gives a "ULR did not match any supported service" error. (Download Episode and Download Complete Series works fine). Looking at the URL there is no indication of any season it it. Maybe that's the reason?

How can I just download sseason 2 + 3 in one go? (Season 1 is already done, so "Download complete series" would download too much.

**Comment by stabbedbybrick** [comment] 2023-12-28 13:23
Please include used command. I can't reproduce your error, so I need to see what your output looks like.

To select multiple full seasons, you separate them by a comma:

`freevine.py get -s s02,s03 https://uktvplay.co.uk/shows/secrets-of-the-london-underground/watch-online`

**Comment by OevreFlataeker** [comment] 2023-12-28 15:08
I was using FreeVine GUI for downloading the full season and it seems the GUI tool is not providing the actual season number to he command line! I'll ping the dev over there to include it!

**Comment by stabbedbybrick** [comment] 2023-12-29 07:05
All right, I'll close this as it's not really related to this project.

**Closed as completed by stabbedbybrick** 2023-12-29 07:05 UTC
Labels: bug
